name: Run build.sh and publish to GHPages

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'

jobs:
  runpublish:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - name: Restore pip cache if available
      uses: actions/cache@v2.1.1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Restore versions.json if available
      uses: actions/cache@v2.1.1
      with:
        path: versions.json
        key: ${{ runner.os }}-versionsjson

    - name: Run publish
      uses: iranzo/gh-action-runpublish@0.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SOURCE_FOLDER: content
        DONOTPUBLISH: True
